// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiwDOvQUprV11NLdY3L2pDm3NOrFfRVO0',
    appId: '1:292970330572:android:93d5661b9349445f004569',
    messagingSenderId: '292970330572',
    projectId: 'must-94dc7',
    storageBucket: 'must-94dc7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8PHpYPX4cuU4KA_F9iXI5MmjuP40Cr7Q',
    appId: '1:292970330572:ios:210dc6d42858beba004569',
    messagingSenderId: '292970330572',
    projectId: 'must-94dc7',
    storageBucket: 'must-94dc7.firebasestorage.app',
    androidClientId: '292970330572-cg80c7oaddgd34ct0frpdi6hkfhqasi1.apps.googleusercontent.com',
    iosClientId: '292970330572-ad58q73hdqrsa69aeug7kkv95mq69dur.apps.googleusercontent.com',
    iosBundleId: 'com.tqniait.mustServiceMan',
  );
}
